### ISSUE TITLE
Ratio in hover over in barcharts in women topic

### ISSUE THREAD

**Issue by datametrician** [presidential-innovation-fellows/midaas-website#19]
Could we add a ratio for female to male in the bar charts? If too difficult please reject.

**Comment by michael-balint** [comment]
@datametrician: I'm pretty sure we have what you're asking for (just requires the right config) - do you mean that you want to show a bar chart of ratios? if so, what would each bar be?

**Comment by datametrician** [comment]
I want when you hover over a bar, instead of showing Male/Female values for the quantile I want it to show male/female and the ratio of the two only on barcharts for women.  In fact, you can do this only on the gender topic

**Comment by datametrician** [comment]
I would love to add this to the general barchart tool as well, but I think that would require more work

**Comment by michael-balint** [comment]
for the generalized version, what would the hover look like there?

**Comment by datametrician** [comment]
The exact same but only in the gender tab section.  Ratios are too weird in any other.

**Comment by michael-balint** [comment]
It's not that this is too difficult, but the fact that it would only be for gender makes the code a bit inconsistent. Closing for now - let's revisit after SX?

**Comment by datametrician** [comment]
Sounds good, should I reopen after SX or create a new ticket @michael-balint

**Comment by michael-balint** [comment]
Let's revisit after SX, I suspect we'll have other feedback that might change things considerably. If not, feel free to reopen this exact one.
