### ISSUE TITLE
Add map widget to tool page

### ISSUE THREAD

**Issue by datametrician** [presidential-innovation-fellows/midaas-website#20]

**Comment by michael-balint** [comment]
@lukad03 do we have an svg icon for a map of the USA?

**Comment by lukad03** [comment]
We don't but I can work on that. The hope is to take these icons down in
favor of something scroll based, and to list the nav items in a left
sidebar for the page.

Proposed Nav
- API
  - Getting Started
  - ...
- MIDAAS JS Library
  - Getting Started
  - Bar Charts
  - Maps
  - ...

On Mon, Mar 7, 2016 at 9:20 AM, Michael Balint notifications@github.com
wrote:

> @lukad03 https://github.com/lukad03 do we have an svg icon for a map of
> the USA?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/presidential-innovation-fellows/midaas-website/issues/20#issuecomment-193267264
> .

## 

Luke Keller
Presidential Innovation Fellow

**Comment by michael-balint** [comment]
Ah, I see. Goes with what you were saying yesterday.

**Comment by michael-balint** [comment]
@lukad03 did this.
