### ISSUE TITLE
Map Tool Exploration

### ISSUE THREAD

**Issue by datametrician** [presidential-innovation-fellows/midaas-website#31]
Finish Map tool that instead of state drop down it has a percentile drop down.

**Comment by michael-balint** [comment]
@datametrician: not clear on this - there should be a quantile drop down when you select a ratio with a map...

**Comment by datametrician** [comment]
When you click on the map tool, the first drop down should be quantiles instead of state, just like women...

Secondarily and a separate issue we need the tabs across the top like in the barchart but a second dropdown https://github.com/presidential-innovation-fellows/midaas-website/issues/32

**Comment by datametrician** [comment]
ergo, when the map widget gets added to the the tool section, the drop down should be percentiles just like in the gender 2nd visualization (the map).

**Comment by datametrician** [comment]
@michael-balint seems this is almost done, what's needed to close this out
