### ISSUE TITLE
Add Features Content to Homepage

### ISSUE THREAD

**Issue by lukad03** [presidential-innovation-fellows/midaas-website#36]
Edit existing content and replace lorem ipsum with legit content.

**Comment by lukad03** [comment]
http://midaas.pif.ninja/

**Comment by datametrician** [comment]
This is more of the banner stuff to the main page

**Comment by datametrician** [comment]
after refreshing page with /?a I see it

**Comment by datametrician** [comment]
Completed https://github.com/presidential-innovation-fellows/midaas-website/commit/e5b85ab4849340b7bb2918994ce35f0bb51f3c48
