### ISSUE TITLE
Toggles not flush with each other and don't show activity

### ISSUE THREAD

**Issue by michael-balint** [presidential-innovation-fellows/midaas-website#45]
Is there a class missing on these? They don't look the same as when you first made them @lukad03 ...

![image](https://cloud.githubusercontent.com/assets/3503731/13571468/349ffe0a-e443-11e5-9e06-7dc3656205e7.png)

**Comment by lukad03** [comment]
Looks like margins have been added. I can fix that

On Mon, Mar 7, 2016 at 9:02 AM, Michael Balint notifications@github.com
wrote:

> Is there a class missing on these? They don't look the same as when you
> first made them @lukad03 https://github.com/lukad03 ...
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/3503731/13571468/349ffe0a-e443-11e5-9e06-7dc3656205e7.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/presidential-innovation-fellows/midaas-website/issues/45
> .

## 

Luke Keller
Presidential Innovation Fellow
