### ISSUE TITLE
Update text on tool pages

### ISSUE THREAD

**Issue by michael-balint** [presidential-innovation-fellows/midaas-website#46]
@datametrician: can you update the description / text on the following pages?

https://github.com/presidential-innovation-fellows/midaas-website/blob/master/src/tools/comparison-chart/index.jade

https://github.com/presidential-innovation-fellows/midaas-website/blob/master/src/tools/choropleth-map/index.jade

**Comment by datametrician** [comment]
Closed https://github.com/presidential-innovation-fellows/midaas-website/commit/61d8c16282c6a179955c356b4da83c38fe5edf53
